name: go ci test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-with: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.9'

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./... # Rekurencyjnie szuka wszystkich plików kończących się na _test.go
